var provedorDetalhe = {
  id: 'arrecadanet',
  nome: 'ArrecadaNet',
  empresa: 'ArrecadaNet',
  stats: {
    municipios: 51
  },
  visaoGeral: [
    { key: 'Nome', val: 'ArrecadaNet' },
    { key: 'Total Municipios', val: '51' },
    { key: 'Estados Atendidos', val: ['GO', 'TO', 'MS', 'MA'], type: 'uf-badges' }
  ],
  configuracaoProvedor: {
    tipoAutenticacao: 2,
    assinaturaDigital: 0,
    helpTipoAutenticacao: {
      certificadoDigital: null,
      usuario: 'Informe o usuário utilizado para acessar o sistema de sua prefeitura.',
      senha: 'Informe a senha utilizada para acessar o sistema de sua prefeitura.',
      token: null,
      fraseSecreta: null
    },
    campoLoginProvedor: 0,
    suportaCancelamentoNFe: true,
    valorCancelamentoNFe: 45,
    usaAEDF: false,
    usaRegimeEspecialTributacao: false,
    usaCodigoServicoMunicipal: true,
    usaDescricaoServico: true,
    usaCNAE: false,
    usaItemListaServico: false,
    helpInscricaoMunicipal: 'A inscrição municipal da empresa deve conter somente números.\r\n\r\nExemplo válido: 11356',
    helpCodigoServicoMunicipal: 'Informe aqui o código de serviço municipal que identifica o serviço prestado na nota fiscal. \r\n\r\nEle possui geralmente 9 dígitos sem formatação.\r\nExemplo válido: 100506213',
    helpDescricaoServico: 'Texto descritivo municipal que descreve o serviço prestado. Essa informação não é transmitida à prefeitura e é utilizada somente na impressão do PDF da nota fiscal',
    suportaEmissaoNFeSemCliente: true,
    suportaEmissaoNFeClienteSemCpf: true,
    suportaEmissaoNFeClienteSemEndereco: true,
    suportaCancelamentoNFeSemCliente: true,
    suportaCancelamentoNFeClienteSemCpf: true,
    enviaEmailCliente: true,
    tempoEsperaParaConsultaLoteNFeEmMinutos: 0,
    naturezasOperacao: [
      { codigo: '1', nome: 'Tributação no municipio' },
      { codigo: '2', nome: 'Tributação fora do municipio' }
    ]
  },
  municipiosLista: {
    'arrecadanet': [
      { nome: 'Abadiânia', uf: 'GO', ibge: '5200100' },
      { nome: 'Almas', uf: 'TO', ibge: '1700400' },
      { nome: 'Alto Horizonte', uf: 'GO', ibge: '5200555' },
      { nome: 'Alvorada do Norte', uf: 'GO', ibge: '5200803' },
      { nome: 'Ananás', uf: 'TO', ibge: '1701002' },
      { nome: 'Araçu', uf: 'GO', ibge: '5201603' },
      { nome: 'Aragoiânia', uf: 'GO', ibge: '5201801' },
      { nome: 'Arapoema', uf: 'TO', ibge: '1702307' },
      { nome: 'Barro Alto', uf: 'GO', ibge: '5203203' },
      { nome: 'Barrolândia', uf: 'TO', ibge: '1703107' },
      { nome: 'Bom Jesus do Tocantins', uf: 'TO', ibge: '1703305' },
      { nome: 'Bonfinópolis', uf: 'GO', ibge: '5203559' },
      { nome: 'Campinorte', uf: 'GO', ibge: '5204706' },
      { nome: 'Campos Belos', uf: 'GO', ibge: '5204904' },
      { nome: 'Campos Lindos', uf: 'TO', ibge: '1703842' },
      { nome: 'Caseara', uf: 'TO', ibge: '1703909' },
      { nome: 'Cezarina', uf: 'GO', ibge: '5205455' },
      { nome: 'Colinas do Tocantins', uf: 'TO', ibge: '1705508' },
      { nome: 'Colméia', uf: 'TO', ibge: '1716703' },
      { nome: 'Corumbá de Goiás', uf: 'GO', ibge: '5205802' },
      { nome: 'Cristianópolis', uf: 'GO', ibge: '5206305' },
      { nome: 'Danivnópolis', uf: 'GO', ibge: '5206909' },
      { nome: 'Eldorado', uf: 'MS', ibge: '5003751' },
      { nome: 'Formoso', uf: 'GO', ibge: '5208103' },
      { nome: 'Gameleira de Goiás', uf: 'GO', ibge: '5208152' },
      { nome: 'Goianápolis', uf: 'GO', ibge: '5208400' },
      { nome: 'Itapaci', uf: 'GO', ibge: '5210901' },
      { nome: 'Itauçu', uf: 'GO', ibge: '5211404' },
      { nome: 'Jandaia', uf: 'GO', ibge: '5211701' },
      { nome: 'Jaraguá', uf: 'GO', ibge: '5211800' },
      { nome: 'Jussara', uf: 'GO', ibge: '5212204' },
      { nome: 'Mambaí', uf: 'GO', ibge: '5212709' },
      { nome: 'Mara Rosa', uf: 'GO', ibge: '5212808' },
      { nome: 'Mateiros', uf: 'TO', ibge: '1712702' },
      { nome: 'Miracema do Tocantins', uf: 'TO', ibge: '1713205' },
      { nome: 'Miranorte', uf: 'TO', ibge: '1713304' },
      { nome: 'Montes Claros de Goiás', uf: 'GO', ibge: '5213707' },
      { nome: 'Nova Veneza', uf: 'GO', ibge: '5215009' },
      { nome: 'Novo Gama', uf: 'GO', ibge: '5215231' },
      { nome: 'Palmeiras de Goiás', uf: 'GO', ibge: '5215702' },
      { nome: 'Peixe', uf: 'TO', ibge: '1716604' },
      { nome: 'Pontalina', uf: 'GO', ibge: '5217708' },
      { nome: 'Porto Alegre do Tocantins', uf: 'GO', ibge: '1718006' },
      { nome: 'Professor Jamil', uf: 'GO', ibge: '5218391' },
      { nome: 'Rialma', uf: 'GO', ibge: '5218607' },
      { nome: 'Santa Fé do Araguaia', uf: 'TO', ibge: '1718865' },
      { nome: 'Santo Antônio de Goiás', uf: 'GO', ibge: '5219738' },
      { nome: 'São João d\'Aliança', uf: 'GO', ibge: '5220009' },
      { nome: 'São Raimundo das Mangabeiras', uf: 'MA', ibge: '2111607' },
      { nome: 'Silvânia', uf: 'GO', ibge: '5220603' },
      { nome: 'Vianópolis', uf: 'GO', ibge: '5222005' }
    ]
  }
};

