var provedorDetalhe = {
  id: 'eelv3',
  nome: 'EeLv3',
  empresa: 'EeLv3',
  stats: {
    municipios: 73
  },
  visaoGeral: [
    { key: 'Nome', val: 'EeLv3' },
    { key: 'Total Municipios', val: '73' },
    { key: 'Estados Atendidos', val: ['ES', 'MG', 'BA', 'RJ', 'PE', 'RO'], type: 'uf-badges' }
  ],
  configuracaoProvedor: {
    tipoAutenticacao: 1,
    assinaturaDigital: 0,
    helpTipoAutenticacao: {
      certificadoDigital: 'Obrigatório a utilização de certificado digital.',
      usuario: null,
      senha: null,
      token: null,
      fraseSecreta: null
    },
    suportaCancelamentoNFe: true,
    valorCancelamentoNFe: 60,
    usaCodigoServicoMunicipal: true,
    usaCNAE: false,
    usaItemListaServico: true,
    helpInscricaoMunicipal: 'Informe sua inscrição municipal.\r\n\r\nExemplos válidos: 06421008 ou 634812-2',
    helpRegimeEspecialTributacao: 'Isso identifica o regime de tributação de sua empresa, se desejar deixar sem nenhuma opção marcada selecione o traço (\\',
    helpCodigoServicoMunicipal: 'Informe aqui o código municipal com 6 dígitos (somente números) que identifica o serviço prestado na nota fiscal.\r\n\r\nEsse código é identificado na sua prefeitura como código de Serviço ou código de serviço nacional. Exemplos válidos: 170901 ou 010201',
    helpDescricaoServico: 'Texto descritivo municipal que descreve o serviço prestado. Essa informação não é transmitida à prefeitura e é utilizada somente na impressão do PDF da nota fiscal.',
    helpCNAE: 'Informe aqui o código CNAE que identifica o serviço prestado na nota fiscal',
    helpItemListaServico: 'Informe aqui o item da lista de serviço, é também um identificador do serviço prestado. \r\n \r\n Você precisa preencher o item da lista de serviço com 5 dígitos mantendo a formatação.\r\n Exemplos válidos: 17.02 ou 08.02',
    suportaEmissaoNFeSemCliente: true,
    suportaEmissaoNFeClienteSemCpf: true,
    suportaEmissaoNFeClienteSemEndereco: false,
    suportaCancelamentoNFeSemCliente: false,
    suportaCancelamentoNFeClienteSemCpf: false,
    tempoEsperaParaConsultaLoteNFeEmMinutos: 0,
    regimesEspecialTributacao: [
      { codigo: '0', nome: ' - ' },
      { codigo: '1', nome: 'Microempresa Municipal' },
      { codigo: '2', nome: 'Estimativa' },
      { codigo: '3', nome: 'Sociedade de Profissionais' },
      { codigo: '4', nome: 'Cooperativa' },
      { codigo: '5', nome: 'MEI - Simples Nacional' },
      { codigo: '6', nome: 'ME EPP - Simples Nacional' }
    ],
    naturezasOperacao: [
      { codigo: '1', nome: 'Exigível' },
      { codigo: '2', nome: 'Não incidência' },
      { codigo: '3', nome: 'Isenção' },
      { codigo: '4', nome: 'Exportação' },
      { codigo: '5', nome: 'Imunidade' },
      { codigo: '6', nome: 'Exigibilidade suspensa por decisão judicial' },
      { codigo: '7', nome: 'Exigilidade suspensa por procedimento administrativo' }
    ]
  },
  municipiosLista: {
    'eelv3': [
      { nome: 'Afonso Cláudio', uf: 'ES', ibge: '3200102' },
      { nome: 'Água Doce do Norte', uf: 'ES', ibge: '3200169' },
      { nome: 'Alegre', uf: 'ES', ibge: '3200201' },
      { nome: 'Alfredo Chaves', uf: 'ES', ibge: '3200300' },
      { nome: 'Almenara', uf: 'MG', ibge: '3101706' },
      { nome: 'Anchieta', uf: 'ES', ibge: '3200409' },
      { nome: 'Aracruz', uf: 'ES', ibge: '3200607' },
      { nome: 'Araçuaí', uf: 'MG', ibge: '3103405' },
      { nome: 'Armação dos Búzios', uf: 'RJ', ibge: '3300233' },
      { nome: 'Baixo Guandu', uf: 'ES', ibge: '3200805' },
      { nome: 'Barreiras', uf: 'BA', ibge: '2903201' },
      { nome: 'Boa Esperança', uf: 'ES', ibge: '3201001' },
      { nome: 'Bom Jesus do Norte', uf: 'ES', ibge: '3201100' },
      { nome: 'Cantagalo', uf: 'RJ', ibge: '3301108' },
      { nome: 'Carmo', uf: 'RJ', ibge: '3301207' },
      { nome: 'Conceição do Castelo', uf: 'ES', ibge: '3201704' },
      { nome: 'Confins', uf: 'MG', ibge: '3117876' },
      { nome: 'Cordeiro', uf: 'RJ', ibge: '3301504' },
      { nome: 'Domingos Martins', uf: 'ES', ibge: '3201902' },
      { nome: 'Duas Barras', uf: 'RJ', ibge: '3301603' },
      { nome: 'Ecoporanga', uf: 'ES', ibge: '3202108' },
      { nome: 'Espera Feliz', uf: 'MG', ibge: '3124203' },
      { nome: 'Fundão', uf: 'ES', ibge: '3202207' },
      { nome: 'Guaçuí', uf: 'ES', ibge: '3202306' },
      { nome: 'Guanhães', uf: 'MG', ibge: '3128006' },
      { nome: 'Guaratinga', uf: 'ES', ibge: '2911808' },
      { nome: 'Ibatiba', uf: 'ES', ibge: '3202454' },
      { nome: 'Ibicoara', uf: 'BA', ibge: '2912202' },
      { nome: 'Iconha', uf: 'ES', ibge: '3202603' },
      { nome: 'Ipiaú', uf: 'BA', ibge: '2913903' },
      { nome: 'Itabirinha', uf: 'MG', ibge: '3131802' },
      { nome: 'Itamaraju', uf: 'BA', ibge: '2915601' },
      { nome: 'Itaocara', uf: 'RJ', ibge: '3302106' },
      { nome: 'Itapemirim', uf: 'ES', ibge: '3202801' },
      { nome: 'Jaboticatubas', uf: 'MG', ibge: '3134608' },
      { nome: 'Jaguaré', uf: 'ES', ibge: '3203056' },
      { nome: 'Jequié', uf: 'BA', ibge: '2918001' },
      { nome: 'João Monlevade', uf: 'MG', ibge: '3136207' },
      { nome: 'João Neiva', uf: 'ES', ibge: '3203130' },
      { nome: 'Linhares', uf: 'ES', ibge: '3203205' },
      { nome: 'Manhuaçu', uf: 'MG', ibge: '3139409' },
      { nome: 'Mantenópolis', uf: 'ES', ibge: '3203304' },
      { nome: 'Marataízes', uf: 'ES', ibge: '3203320' },
      { nome: 'Marechal Floriano', uf: 'ES', ibge: '3203346' },
      { nome: 'Mimoso do Sul', uf: 'ES', ibge: '3203403' },
      { nome: 'Montanha', uf: 'ES', ibge: '3203502' },
      { nome: 'Monte Santo de Minas', uf: 'MG', ibge: '3143203' },
      { nome: 'Nova Resende', uf: 'MG', ibge: '3145109' },
      { nome: 'Nova Venécia', uf: 'ES', ibge: '3203908' },
      { nome: 'Pedro Canário', uf: 'ES', ibge: '3204054' },
      { nome: 'Petrolina', uf: 'PE', ibge: '2611101' },
      { nome: 'Piúma', uf: 'ES', ibge: '3204203' },
      { nome: 'Planalto', uf: 'BA', ibge: '2925006' },
      { nome: 'Poções', uf: 'BA', ibge: '2925105' },
      { nome: 'Porto Velho', uf: 'RO', ibge: '1100205' },
      { nome: 'Prado', uf: 'BA', ibge: '2925501' },
      { nome: 'Rio Piracicaba', uf: 'MG', ibge: '3155702' },
      { nome: 'Santa Bárbara do Leste', uf: 'MG', ibge: '3157252' },
      { nome: 'Santa Maria de Jetibá', uf: 'ES', ibge: '3204559' },
      { nome: 'Santa Teresa', uf: 'ES', ibge: '3204609' },
      { nome: 'São Gabriel da Palha', uf: 'ES', ibge: '3204708' },
      { nome: 'São João do Manteninha', uf: 'MG', ibge: '3162575' },
      { nome: 'São João Evangelista', uf: 'MG', ibge: '3162807' },
      { nome: 'São Mateus', uf: 'ES', ibge: '3204906' },
      { nome: 'Simões Filho', uf: 'BA', ibge: '2930709' },
      { nome: 'Sooretama', uf: 'ES', ibge: '3205010' },
      { nome: 'Taiobeiras', uf: 'MG', ibge: '3168002' },
      { nome: 'Três Corações', uf: 'MG', ibge: '3169307' },
      { nome: 'Valença', uf: 'BA', ibge: '2932903' },
      { nome: 'Venda Nova do Imigrante', uf: 'ES', ibge: '3205069' },
      { nome: 'Viana', uf: 'ES', ibge: '3205101' },
      { nome: 'Vila Valério', uf: 'ES', ibge: '3205176' },
      { nome: 'Vitória da Conquista', uf: 'BA', ibge: '2933307' }
    ]
  }
};

