var provedorDetalhe = {
  id: 'govbrv3',
  nome: 'GOVBRv3',
  empresa: 'GOVBRv3',
  stats: {
    municipios: 77
  },
  visaoGeral: [
    { key: 'Nome', val: 'GOVBRv3' },
    { key: 'Total Municipios', val: '77' },
    { key: 'Estados Atendidos', val: ['RS', 'SP', 'PR', 'RJ', 'MG'], type: 'uf-badges' }
  ],
  configuracaoProvedor: {
    tipoAutenticacao: 1,
    assinaturaDigital: 2,
    helpTipoAutenticacao: {
      certificadoDigital: 'Sua prefeitura exige a utilização de certificado digital, portanto, inclua aqui o arquivo de seu certificado A1.',
      usuario: null,
      senha: null,
      token: null,
      fraseSecreta: null
    },
    suportaCancelamentoNFe: true,
    valorCancelamentoNFe: 30,
    usaAEDF: false,
    usaRegimeEspecialTributacao: true,
    usaCodigoServicoMunicipal: true,
    usaDescricaoServico: false,
    usaCNAE: true,
    usaNBS: true,
    usaItemListaServico: false,
    usaNaturezaOperacao: true,
    helpInscricaoMunicipal: 'A inscrição municipal da empresa deve conter de 8 dígitos (com formatação).\r\n\r\nExemplo válido: 14.05.01',
    helpRegimeEspecialTributacao: 'Isso identifica o regime especial de tributação de sua empresa',
    helpCodigoServicoMunicipal: 'Informe aqui o código de serviço municipal que identifica o serviço prestado na nota fiscal. Exemplo: 07.01.01',
    helpCNAE: 'Informe aqui o CNAE o Serviço municipal conforme usado no portal de NFS-e da prefeitura. Exemplo: 4329103, 1813001',
    suportaEmissaoNFeSemCliente: true,
    suportaEmissaoNFeClienteSemCpf: false,
    suportaEmissaoNFeClienteSemEndereco: true,
    suportaCancelamentoNFeSemCliente: true,
    suportaCancelamentoNFeClienteSemCpf: false,
    enviaEmailCliente: false,
    suportaConsultaSequencialRps: true,
    numeroNotasPorLote: 1,
    regimesEspecialTributacao: [
      { codigo: '0', nome: ' - ' },
      { codigo: '1', nome: 'Microempresa Municipal' },
      { codigo: '2', nome: 'Estimativa' },
      { codigo: '3', nome: 'Sociedade de Profissionais' },
      { codigo: '4', nome: 'Cooperativa' },
      { codigo: '5', nome: 'MEI - Simples Nacional' },
      { codigo: '6', nome: 'ME EPP - Simples Nacional' }
    ],
    naturezasOperacao: [
      { codigo: '1', nome: 'Operação tributável' },
      { codigo: '2', nome: 'Imunidade' },
      { codigo: '3', nome: 'Exportação de Serviço' },
      { codigo: '4', nome: 'Não incidência' }
    ]
  },
  municipiosLista: {
    'govbrv3': [
      { nome: 'Agudo', uf: 'RS', ibge: '4300109' },
      { nome: 'Alegrete', uf: 'RS', ibge: '4300406' },
      { nome: 'Álvares Machado', uf: 'SP', ibge: '3501301' },
      { nome: 'Araruama', uf: 'RJ', ibge: '3300209' },
      { nome: 'Arroio do Sal', uf: 'RS', ibge: '4301057' },
      { nome: 'Boituva', uf: 'SP', ibge: '3507001' },
      { nome: 'Cachoeira do Sul', uf: 'RS', ibge: '4303004' },
      { nome: 'Caeté', uf: 'MG', ibge: '3110004' },
      { nome: 'Canguçu', uf: 'RS', ibge: '4304507' },
      { nome: 'Caratinga', uf: 'MG', ibge: '3113404' },
      { nome: 'Chopinzinho', uf: 'PR', ibge: '4105409' },
      { nome: 'Conchas', uf: 'SP', ibge: '3512308' },
      { nome: 'Contagem', uf: 'MG', ibge: '3118601' },
      { nome: 'Coronel Vivida', uf: 'PR', ibge: '4106506' },
      { nome: 'Divinolândia', uf: 'SP', ibge: '3513900' },
      { nome: 'Dom Pedrito', uf: 'RS', ibge: '4306601' },
      { nome: 'Eldorado do Sul', uf: 'RS', ibge: '4306767' },
      { nome: 'Encruzilhada do Sul', uf: 'RS', ibge: '4306908' },
      { nome: 'Feliz', uf: 'RS', ibge: '4308102' },
      { nome: 'Getúlio Vargas', uf: 'RS', ibge: '4308904' },
      { nome: 'Guaporé', uf: 'RS', ibge: '4309407' },
      { nome: 'Guarani das Missões', uf: 'RS', ibge: '4309506' },
      { nome: 'Ibiraiaras', uf: 'RS', ibge: '4309902' },
      { nome: 'Ijuí', uf: 'RS', ibge: '4310207' },
      { nome: 'Itabira', uf: 'MG', ibge: '3131703' },
      { nome: 'Italva', uf: 'RJ', ibge: '3302056' },
      { nome: 'Itapejara d\'Oeste', uf: 'PR', ibge: '4111209' },
      { nome: 'Itaperuna', uf: 'RJ', ibge: '3302205' },
      { nome: 'Jacarezinho', uf: 'PR', ibge: '4111803' },
      { nome: 'Jarinu', uf: 'SP', ibge: '3525201' },
      { nome: 'Jesuítas', uf: 'PR', ibge: '4112751' },
      { nome: 'Júlio de Castilhos', uf: 'RS', ibge: '4311205' },
      { nome: 'Macuco', uf: 'RJ', ibge: '3302452' },
      { nome: 'Miracema', uf: 'RJ', ibge: '3303005' },
      { nome: 'Mirassol', uf: 'SP', ibge: '3530300' },
      { nome: 'Moema', uf: 'MG', ibge: '3142403' },
      { nome: 'Monte Alegre do Sul', uf: 'SP', ibge: '3531209' },
      { nome: 'Morro Reuter', uf: 'RS', ibge: '4312476' },
      { nome: 'Novo Cabrais', uf: 'RS', ibge: '4313391' },
      { nome: 'Palmares do Sul', uf: 'RS', ibge: '4313656' },
      { nome: 'Palmital', uf: 'SP', ibge: '3535309' },
      { nome: 'Pantano Grande', uf: 'RS', ibge: '4313953' },
      { nome: 'Paraíba do Sul', uf: 'RJ', ibge: '3303708' },
      { nome: 'Pato Branco', uf: 'PR', ibge: '4118501' },
      { nome: 'Pedro Osório', uf: 'RS', ibge: '4314209' },
      { nome: 'Pejuçara', uf: 'RS', ibge: '4314308' },
      { nome: 'Picada Café', uf: 'RS', ibge: '4314423' },
      { nome: 'Pindorama', uf: 'SP', ibge: '3538105' },
      { nome: 'Piratini', uf: 'RS', ibge: '4314605' },
      { nome: 'Porecatu', uf: 'PR', ibge: '4120002' },
      { nome: 'Porto Feliz', uf: 'SP', ibge: '3540606' },
      { nome: 'Presidente Bernardes', uf: 'SP', ibge: '3541208' },
      { nome: 'Presidente Epitácio', uf: 'SP', ibge: '3541307' },
      { nome: 'Regente Feijó', uf: 'SP', ibge: '3542404' },
      { nome: 'Rio Pardo', uf: 'RS', ibge: '4315701' },
      { nome: 'Rolândia', uf: 'PR', ibge: '4122404' },
      { nome: 'Rosário do Sul', uf: 'RS', ibge: '4316402' },
      { nome: 'Salto do Lontra', uf: 'PR', ibge: '4123006' },
      { nome: 'Santa Terezinha de Itaipu', uf: 'PR', ibge: '4124053' },
      { nome: 'Santa Vitória do Palmar', uf: 'RS', ibge: '4317301' },
      { nome: 'São Gabriel', uf: 'RS', ibge: '4318309' },
      { nome: 'São Gonçalo do Rio Abaixo', uf: 'MG', ibge: '3161908' },
      { nome: 'São Lourenço do Sul', uf: 'RS', ibge: '4318804' },
      { nome: 'São Pedro', uf: 'SP', ibge: '3550407' },
      { nome: 'São Roque', uf: 'SP', ibge: '3550605' },
      { nome: 'Saquarema', uf: 'RJ', ibge: '3305505' },
      { nome: 'Sentinela do Sul', uf: 'RS', ibge: '4320354' },
      { nome: 'Silva Jardim', uf: 'RJ', ibge: '3305604' },
      { nome: 'Tapera', uf: 'RS', ibge: '4321006' },
      { nome: 'Três Barras do Paraná', uf: 'PR', ibge: '4127858' },
      { nome: 'Três Coroas', uf: 'RS', ibge: '4321709' },
      { nome: 'Triunfo', uf: 'RS', ibge: '4322004' },
      { nome: 'Tuiuti', uf: 'SP', ibge: '3554953' },
      { nome: 'Uruguaiana', uf: 'RS', ibge: '4322400' },
      { nome: 'Vacaria', uf: 'RS', ibge: '4322509' },
      { nome: 'Varre-Sai', uf: 'RJ', ibge: '3306156' },
      { nome: 'Viamão', uf: 'RS', ibge: '4323002' }
    ]
  }
};

